# Generated by Django 5.0.6 on 2024-07-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_name', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('idNr', models.CharField(default='', max_length=13)),
                ('initials', models.CharField(default='', max_length=10)),
                ('title', models.CharField(default='', max_length=10)),
                ('cellNr', models.CharField(default='', max_length=12)),
                ('occupation', models.CharField(default='', max_length=100)),
                ('current_employer', models.CharField(default='', max_length=100)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(default='', max_length=5)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dependent_code', models.IntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.aid')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.member')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.member')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergie', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.member')),
            ],
        ),
        migrations.AddField(
            model_name='aid',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.member'),
        ),
    ]
